version: 0.0
os: linux
files:
  - source: /
    #   version2 path : destination: /home/ec2-user/app/step2/zip/
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes
permissions:
  - object: / # / => step3/zip 경로로 변경
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: stop.sh
      timeout : 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user